### ISSUE TITLE
mkdir /var/www: read-only file system.

### ISSUE THREAD

**Issue by spekulatius** [kamerk22/laravel-alpine#15]
Hey @kamerk22 

when executing the `docker run` command I get the following error:

```
11:48 # docker run -v $(pwd):/var/www kamerk22/laravel-alpine:latest "composer install --prefer-dist"
docker: Error response from daemon: error while creating mount source path '/var/www/dev.project.com': mkdir /var/www: read-only file system.
ERRO[0000] error waiting for container: context canceled 
```

Not sure if I do something wrong. Any idea on the reason?

Cheers!

**Comment by kamerk22** [comment]
@spekulatius I'm not sure. 
Are you using snap version or official docker-ce?

[Might help](https://stackoverflow.com/a/52566470)

**Comment by spekulatius** [comment]
Hey @kamerk22 

I'm using the regular version coming with my Linux via apt-get:

```
12:13 # docker -v
Docker version 19.03.11, build dd360c7
```

Does this help? Which version is required/recommended?

**Comment by kamerk22** [comment]
@spekulatius I can't reproduce the issue. 
Instead of ${pwd} in -v, try providing the full path instead

**Comment by spekulatius** [comment]
Hmm okay @kamerk22. I've tried the full path with the same error message.

I'm a bit confused about the path in the error message - `/var/www` is in the container, isn't it?

Can you share what permissions your folders usually have (`ls -la` in a project)?

**Comment by spekulatius** [comment]
I think the snap-installed docker packages aren't working - I've removed them and reinstalled from the .deb packages on the [docker websites](https://download.docker.com/linux/ubuntu/dists/)  and it resolved this.
