### ISSUE TITLE
/usr/local/bin/docker-php-entrypoint: exec: line 9: composer install --prefer-dist: not found

### ISSUE THREAD

**Issue by spekulatius** [kamerk22/laravel-alpine#16]
Hey @kamerk22 

after resolving #15 and get it kinda working I get this error:

```
/usr/local/bin/docker-php-entrypoint: exec: line 9: composer install --prefer-dist: not found
```

Any idea what the issue is?

In advance: thanks for your help,
Peter

**Comment by kamerk22** [comment]
Here's how I'm using this Image as base @spekulatius 

```Dockerfile
FROM kamerk22/laravel-alpine:7.2-mysql-nginx

COPY composer.json composer.json
COPY composer.lock composer.lock

// To speed up downloading of deps
RUN composer global require hirak/prestissimo

// Then finally install required package
RUN composer install --prefer-dist --no-scripts --no-autoloader && rm -rf /root/.composer

// Copy code to container. You can mount dir
COPY --chown=www-data:www-data . .

// Fix required permission for cache and storage
RUN chgrp -R www-data /var/www/storage /var/www/bootstrap/cache
RUN chmod -R 775 /var/www/storage /var/www/bootstrap/cache

RUN composer dump-autoload --no-scripts --optimize
RUN ln -s /var/www/storage/app/ /var/www/public/storage
```

This repo contain the image required for any laravel project as base. 
However you've to add your `Dockerfile` on top of that to make it work the way you want.

You can add this `Dockerfile` add try to build the image. If it'll work then you can change the file and steps.
I suggest you to use Docker Compose for volume mount and use this as build image.

**Comment by spekulatius** [comment]
Thank you that helps @kamerk22 - it shows I'm new to docker. One follow up question: I'm using Laravel Nova which comes from a private composer repository. For this it requires login credentials. How would I symlink/copy my personal `~/.composer`-directory instead of the empty containers one' in? I've tried `COPY` and `ADD` without much success...

**Comment by kamerk22** [comment]
@spekulatius You don't have to copy your local composer, instead use bind mount.

Directly mount your local composer path to your container. This way composer can access your private deps.

**Comment by spekulatius** [comment]
Can I use a mount with `docker build`? This is where `composer install` is run and I couldn't find any indication on how to use bind a directory @kamerk22 

For context: currently, I'm using this approach:

```
docker build -t "laravel:Dockerfile" .
docker run "laravel"
```

**Comment by kamerk22** [comment]
@spekulatius 
You can't mount volume while building. 
You can do two things.
1. Copy .composer secret while building it from host ( easy and preferred   )
2. Use own `Entrypoint.sh` where you can remove the composer install part while building, and install composer deps in entrypoint. Entrypoint run when container run so this way you can bind volume and install after. ( You've to wait for contaienr to install deps then it'll start serving )

**Comment by spekulatius** [comment]
Okay, copying in a whole folder isn't doable easily @kamerk22? This way I could also use my local package cache too - speeding up builds

**Comment by kamerk22** [comment]
@spekulatius You can easily copy local composer folder in dockerfile and yes it'll use local cache too

**Comment by spekulatius** [comment]
I've tried `COPY /home/peter/.composer /root/.composer/` without success. With this I get:

`COPY failed: stat /var/lib/docker/tmp/docker-builder433628094/home/peter/.composer: no such file or directory` @kamerk22

**Comment by kamerk22** [comment]
@spekulatius 
Docker will look for file in build context. On your case it's not inside current dir so it'll fail.

Look for including file outside build context in Docker. You'll find couple of workaround.

**Comment by spekulatius** [comment]
Awesome, thanks for pointing me in the right direction @kamerk22! I've managed to solve it by passing in the whole json and writing it to a file during build:

```
docker build -t laravel -f ./Dockerfile --build-arg COMPOSER_AUTH="$(cat ~/.composer/auth.json)" .
```

In the Dockerfile I've added:

```
# Copy any existing auths over.
ARG COMPOSER_AUTH
RUN echo "${COMPOSER_AUTH}" > /root/.composer/auth.json
```

Now the container runs:

```
13:36 $ docker run laravel
2020-10-21 09:37:02,401 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2020-10-21 09:37:02,401 INFO Included extra file "/etc/supervisor.d/master.ini" during parsing
2020-10-21 09:37:02,406 INFO RPC interface 'supervisor' initialized
2020-10-21 09:37:02,407 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-10-21 09:37:02,407 INFO supervisord started with pid 1
2020-10-21 09:37:03,412 INFO spawned: 'nginx' with pid 8
2020-10-21 09:37:03,418 INFO spawned: 'crond' with pid 9
2020-10-21 09:37:03,426 INFO spawned: 'php' with pid 10
2020-10-21 09:37:04,556 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-10-21 09:37:04,557 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-10-21 09:37:04,557 INFO success: php entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

But I'm unsure how to access it - I couldn't find any information about the port used and the commonly used ports don't seem to work. What am I missing @kamerk22 ?

**Comment by kamerk22** [comment]
@spekulatius As per log eveything is up and running. Nginx default port is 80.
When you run the container you've to expose the port.
`docker run -p 8080:80 {name_of_image}`

Then you can access at localhost:8080

**Comment by spekulatius** [comment]
Ah okay, in the other docker images I've seen there is a `EXPOSE` command at the end - that's what I was looking for. Learning about docker I wonder if there is any particular reason for not following this approach?

**Comment by spekulatius** [comment]
Hey @kamerk22 

I've tried it and get no response from the container at all. Is there something else I need to tweak/add?

Thanks for all your help to get so far!

Cheers,
Peter

**Comment by kamerk22** [comment]
@spekulatius 

Can you try ssh into container

`docker exec -it [container_id] sh`

And then run `curl http://localhost:80`

**Comment by spekulatius** [comment]
> `docker exec -it [container_id] sh`
> 
> And then run `curl http://localhost:80`

That works - I can see the HTML output for my homepage. 

And I got the issue now - read the ports as `container:host` - got it now. Under `8080` it works. Stupid mistake.

Again, thanks for all your help! I'll fiddle around and hopefully won't need to bother you more ;)
