### ISSUE TITLE
Redis?

### ISSUE THREAD

**Issue by spekulatius** [kamerk22/laravel-alpine#17]
Hey @kamerk22 

is it viable to add redis? 

I've tried a few ways but didn't get to a working solution.

Cheers!

**Comment by kamerk22** [comment]
@spekulatius I suggest you to run seprate redis container, offical or bitnami.

I'm already using this and didn't face any issue.
It'll be a lot easier to run and maintain

**Comment by spekulatius** [comment]
Okay, good idea
