### ISSUE TITLE
/var/www contains file/folders that are not part of the code

### ISSUE THREAD

**Issue by oxodesign** [kamerk22/laravel-alpine#18]
Hi

Thanks for this package!

Im just wondering why does /var/www contain following file/folders: "15", "html" and "localhost", see image: https://share.getcloudapp.com/8LurKzx4

**Comment by kamerk22** [comment]
Yes, I checked with the base image `html` is the default folder. apart from that 15 and localhost is created during the build process. I've to check in detail.
