### ISSUE TITLE
You must set up the project dependencies using `composer install`

### ISSUE THREAD

**Issue by oxodesign** [kamerk22/laravel-alpine#20]
When running "composer dump-autoload --no-scripts --optimize" im getting this error:
---
You must set up the project dependencies using `composer install`
See https://getcomposer.org/download/ for instructions on installing Composer
---

**Comment by kamerk22** [comment]
If you can check again with newly build images
https://github.com/kamerk22/laravel-alpine/pkgs/container/laravel-alpine/versions
